/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'upvotes' : bigint,
  'content' : string,
  'pageContext' : PageContext,
  'timestamp' : bigint,
  'authorAlias' : string,
}
export type CommentId = bigint;
export interface CommentInput {
  'content' : string,
  'pageContext' : PageContext,
}
export type JobId = string;
export interface LastForgedTask { 'jobId' : JobId, 'taskDescription' : string }
export type PageContext = string;
export type Rating = bigint;
export interface RatingSubmission { 'jobId' : JobId, 'rating' : Rating }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[CommentInput], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAlias' : ActorMethod<[], string>,
  'getCallerRating' : ActorMethod<[JobId], [] | [Rating]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsByPageContext' : ActorMethod<[PageContext], Array<Comment>>,
  'getLastForgedTask' : ActorMethod<[], [] | [LastForgedTask]>,
  'getRating' : ActorMethod<[JobId, Principal], [] | [Rating]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setLastForgedTask' : ActorMethod<[LastForgedTask], undefined>,
  'submitRating' : ActorMethod<[RatingSubmission], undefined>,
  'upvoteComment' : ActorMethod<[CommentId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];