/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PageContext = IDL.Text;
export const CommentInput = IDL.Record({
  'content' : IDL.Text,
  'pageContext' : PageContext,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobId = IDL.Text;
export const Rating = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Comment = IDL.Record({
  'upvotes' : IDL.Nat,
  'content' : IDL.Text,
  'pageContext' : PageContext,
  'timestamp' : IDL.Int,
  'authorAlias' : IDL.Text,
});
export const LastForgedTask = IDL.Record({
  'jobId' : JobId,
  'taskDescription' : IDL.Text,
});
export const RatingSubmission = IDL.Record({
  'jobId' : JobId,
  'rating' : Rating,
});
export const CommentId = IDL.Nat;

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([CommentInput], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAlias' : IDL.Func([], [IDL.Text], []),
  'getCallerRating' : IDL.Func([JobId], [IDL.Opt(Rating)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsByPageContext' : IDL.Func(
      [PageContext],
      [IDL.Vec(Comment)],
      ['query'],
    ),
  'getLastForgedTask' : IDL.Func([], [IDL.Opt(LastForgedTask)], ['query']),
  'getRating' : IDL.Func([JobId, IDL.Principal], [IDL.Opt(Rating)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setLastForgedTask' : IDL.Func([LastForgedTask], [], []),
  'submitRating' : IDL.Func([RatingSubmission], [], []),
  'upvoteComment' : IDL.Func([CommentId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PageContext = IDL.Text;
  const CommentInput = IDL.Record({
    'content' : IDL.Text,
    'pageContext' : PageContext,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobId = IDL.Text;
  const Rating = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Comment = IDL.Record({
    'upvotes' : IDL.Nat,
    'content' : IDL.Text,
    'pageContext' : PageContext,
    'timestamp' : IDL.Int,
    'authorAlias' : IDL.Text,
  });
  const LastForgedTask = IDL.Record({
    'jobId' : JobId,
    'taskDescription' : IDL.Text,
  });
  const RatingSubmission = IDL.Record({ 'jobId' : JobId, 'rating' : Rating });
  const CommentId = IDL.Nat;
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([CommentInput], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAlias' : IDL.Func([], [IDL.Text], []),
    'getCallerRating' : IDL.Func([JobId], [IDL.Opt(Rating)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsByPageContext' : IDL.Func(
        [PageContext],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getLastForgedTask' : IDL.Func([], [IDL.Opt(LastForgedTask)], ['query']),
    'getRating' : IDL.Func(
        [JobId, IDL.Principal],
        [IDL.Opt(Rating)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setLastForgedTask' : IDL.Func([LastForgedTask], [], []),
    'submitRating' : IDL.Func([RatingSubmission], [], []),
    'upvoteComment' : IDL.Func([CommentId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };